name: Национальные биоразнообразие и биобезопасность России
lang: ru
name_en: National Biodiversity and Biosafety of Russia
name_ru: Национальное биоразнообразие и биобезопасность России
permalink: /posts/:title
repository:  natbio-ru/natbio-ru.github.io 