title:          "Натбио"
description:    "Национальные биоразнообразие и биобезопасность России"
lang:           ru
name_en:        National Biodiversity and Biosafety of Russia
name_ru:        Национальное биоразнообразие и биобезопасность России

date_format:    "%b %-d, %Y"

# jekyll-paginate configuration
paginate:       5

# Build settings
markdown:       kramdown
highlighter:    rouge
permalink:      /posts/:title
plugins:        [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Styles
#sass:
#  sass_dir:     assets/css
#  style:        :nested

# RSS/Atom (this is where Jekyll-Feed gets configuration information)
author:         "Натбио"
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml