title:          "Натбио"
description:    "Национальная биобезопасность России"
lang:           ru

date_format:    "%b %-d, %Y"
months:
    - Январь
    - Февраль
    - Март
    - Апрель
    - Май
    - Июнь
    - Июль
    - Август
    - Сентябрь
    - Октябрь
    - Ноябрь
    - Декабрь

# jekyll-paginate configuration
paginate:       5

collection:
    posts:
        #output: true
        #permalink: /:collection/:name:html

# Build settings
markdown:       kramdown
highlighter:    rouge
plugins:        [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]


# RSS/Atom (this is where Jekyll-Feed gets configuration information)
author:         "Натбио"
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml