title:          "Натбио"
description:    "Национальная биобезопасность России"
lang:           ru
name_en:        National Biosafety of Russia
name_ru:        Национальная биобезопасность России

date_format:    "%b %-d, %Y"
months:
    - Январь
    - Февраль
    - Март
    - Апрель
    - Май
    - Июнь
    - Июль
    - Август
    - Сентябрь
    - Октябрь
    - Ноябрь
    - Декабрь

# jekyll-paginate configuration
paginate:       5

# Build settings
markdown:       kramdown
highlighter:    rouge
permalink:      /:year/:month/:date/:title/
plugins:        [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Styles
#sass:
#  sass_dir:     assets/css
#  style:        :nested

# RSS/Atom (this is where Jekyll-Feed gets configuration information)
author:         "Натбио"
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml