title:          "Натбио"
description:    "Национальная биобезопасность России"
lang:           ru
baseurl:        https://github.com/natbio-ru/natbio-ru.github.io/raw/master/

date_format:    "%b %-d, %Y"
months:
    - Январь
    - Февраль
    - Март
    - Апрель
    - Май
    - Июнь
    - Июль
    - Август
    - Сентябрь
    - Октябрь
    - Ноябрь
    - Декабрь

# jekyll-paginate configuration
paginate:       5

collections:
    posts:
        output: true
        permalink: /:collection/:year/:month/:day/:title.html

# Build settings
markdown:       kramdown
highlighter:    rouge
plugins:        [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]


# RSS/Atom (this is where Jekyll-Feed gets configuration information)
author:         "Натбио"
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
